import Head from "next/head";
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import TextField from '@mui/material/TextField'
import { useState } from "react";
import { GoogleIcon, PasswordInput } from "@/components";
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{
        display: 'flex',
        alignItems: 'center',

      }}>
        <Box sx={{ display: { xs: 'none', sm: 'none', md: 'flex' } }}>
          <Image
            src={'images/img_login.svg'}
            width={525}
            height={832}
            loading="lazy"
            alt="Imagem de login"
          />
        </Box>

        <Box
          sx={{
            width: 550,
            mx: 'auto',
            textAlign: 'center',
            height: { xs: '100vh' },
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            px: 3
          }}
        >
          <Box>
            <Typography
              variant="h3"
              color="primary"
              sx={{ fontSize: { xs: '24px', sm: '34px', md: '48px' } }}
            >
              Entre no Orange Portfólio
            </Typography>

            <Button
              sx={{
                textTransform: 'none',
                my: 4,
                boxShadow: '0px 2px 5px #00000030',
                color: '#00000054'
              }}
            >
              <GoogleIcon />
              <Typography
                variant="body1"
                sx={{
                  ml: 3,
                  fontWeight: 700,
                }}
              >
                Entrar com Google
              </Typography>
            </Button>
          </Box>

          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column'
            }}>
            <Typography
              variant="h5"
              sx={{
                color: 'neutral.110',
                fontSize: { xs: '16px', sm: '20px', md: '24px' }
              }}
            >
              Faça login com email
            </Typography>
            <TextField
              id="email"
              label="Email address"
              sx={{ my: 2 }}
              value={email}
              onChange={e => setEmail(e.target.value)}
            />
            <PasswordInput
              password={password}
              handlePassword={e => setPassword(e.target.value)}
            />

            <Button
              variant="contained"
              color="secondary"
              sx={{ mt: 2, mb: '18px' }}
            >
              Entrar
            </Button>
            <Link
              href={'/'}
              style={{ textDecoration: 'none' }}
            >
              <Typography
                variant="subtitle1"
                sx={{
                  color: "neutral.100",
                  textDecoration: 'none'
                }}
              >
                Cadastre-se
              </Typography>
            </Link>
          </Box>

        </Box>
      </main>
    </>
  );
}
